version: '3.8'

services:
  personal-api:
    build: .
    ports:
      - "3030:3030"
    environment:
      - RUST_LOG=info
      - BREVO_API_KEY=${BREVO_API_KEY}
      - BREVO_SENDER_EMAIL=${BREVO_SENDER_EMAIL}
      - BREVO_SENDER_NAME=${BREVO_SENDER_NAME}
      - CONTACT_RECIPIENT_EMAIL=${CONTACT_RECIPIENT_EMAIL}
    volumes:
      - ./assets:/app/assets:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
